# Application
spring.application.name=EnglishMate

# Server
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/englishmate?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
